let a = prompt("Vật Lý" );
let b = prompt("Hóa Học");
let c = prompt("Sinh Học");
let a1 = parseInt(a);
let b1 = parseInt(b);
let c1 = parseInt(c);
let d = a1 + b1 +c1;
let f = d / 3;
document.write("Tổng 3 môn: " + d);
document.write("Trung bình 3 môn: " + f);